In [8]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [9]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [10]:
def load_array(data_arrays, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [11]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)
next(iter(data_iter))

[tensor([[-1.3448,  0.1404],
         [ 1.5538, -0.7523],
         [-0.7197,  0.8882],
         [-0.3931,  0.9607],
         [ 1.4013, -1.3818],
         [ 0.5778, -0.5423],
         [ 1.8975, -0.0083],
         [ 0.3016, -0.0449],
         [-0.1610,  0.7129],
         [ 0.6403,  2.4883]]),
 tensor([[ 1.0351],
         [ 9.8574],
         [-0.2749],
         [ 0.1438],
         [11.6984],
         [ 7.2127],
         [ 8.0229],
         [ 4.9571],
         [ 1.4334],
         [-2.9914]])]

上边准备好了数据

下边开始训练

In [12]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

In [13]:
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [14]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(epoch, l)

0 tensor(0.0003, grad_fn=<MseLossBackward0>)
1 tensor(0.0001, grad_fn=<MseLossBackward0>)
2 tensor(0.0001, grad_fn=<MseLossBackward0>)


In [15]:
w = net[0].weight.data
print(w, true_w)
b = net[0].bias.data
print(b, true_b)

tensor([[ 2.0013, -3.3999]]) tensor([ 2.0000, -3.4000])
tensor([4.2004]) 4.2
