In [1]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('axis=0: ', np.max(arr, axis=0))  # axis=0 表示沿着行方向压缩，对每一列求最大值
print('axis=0, keepdims=True: ', np.max(arr, axis=0, keepdims=True))  # keepdims=True, 计算完之后，不把被压缩掉的维度删掉，而是保留为长度 1 的维度
print('axis=1: ', np.max(arr, axis=1))  # axis=0 表示沿着行方向压缩，对每一列求最大值
print('axis=1, keepdims=True: ', np.max(arr, axis=1, keepdims=True))  # axis=1 表示沿着列方向压缩，对每一行求最大值

[[1 2 3]
 [4 5 6]]
axis=0:  [4 5 6]
axis=0, keepdims=True:  [[4 5 6]]
axis=1:  [3 6]
axis=1, keepdims=True:  [[3]
 [6]]


In [9]:
print(arr - np.max(arr, axis=1, keepdims=True))  # Broadcasting，广播机制

[[-2 -1  0]
 [-2 -1  0]]


In [10]:
print(arr.reshape(1, -1))  # -1 表示：这一维的大小由 NumPy 自动推导。

[[1 2 3 4 5 6]]


In [12]:
print(np.arange(1 * 1 * 4 * 4))
print(np.arange(1 * 1 * 4 * 4).reshape(1, 1, 4, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]]]
